# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # - name: Docker pull google/cloud-sdk:latest
      #   run: docker pull --quiet google/cloud-sdk:latest
      #   if: runner.os == 'Linux'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info

      # - name: Update GCloud Components
      #   run: gcloud components update --quiet

      - name: Install GCloud beta
        run: gcloud components install beta --quiet

      - name: Install cloud-datastore-emulator
        run: gcloud components install cloud-datastore-emulator --quiet

      - run: npm run install
      - run: npm run test
